inbound:
  - path: /abc/*
    group: group_1
  - path: /cde/*
    group: group_2

outbound:
  - group: group_1
    servers:
      - 127.0.0.1:8080
      - localhost:8181
  - group: group_2
    servers:
      - test:8080
      - test2:8181