inbound:
  - path: /todos/*
    group: group_1
  - path: /cde/*
    group: group_2

outbound:
  - group: group_1
    servers:
      - https://jsonplaceholder.typicode.com
  - group: group_2
    servers:
      - http://test:8082
      - http://test2:8181/test