inbound:
  - path: /abc/*
    group: group_1
  - path: /cde/*
    group: group_2

outbound:
  - group: group_1
    servers:
      - http://127.0.0.1:8080
      - http://localhost:8182
  - group: group_2
    servers:
      - http://test:8082
      - http://test2:8181/test