# service configuration
service:
  # ip address
  ip: localhost
  # bind port
  port: 8080
  # worker threads
  workers: 6
  # dev mode - will enable only terminal logger
  dev_mode: true

# inbound paths
inbound:
  # match path to group
  - path: /tools/*
    group: group_1
  # match path to group
  - path: /cde/*
    group: group_2

# outbound backup groups
outbound:
  - group: group_1
    # timeout for all servers in this group
    timeout: 60
    # backend servers for this group
    # round robin balancing to all servers
    servers:
      - https://www.rust-lang.org/
  - group: group_2
    servers:
      - http://test:8082
      - http://test2:8181/test