inbound:
  - path: /abc/*
    group: group_1
  - path: /cde/*
    group: group_2

outbound:
  - group: group_1
    timeout: 60
    servers:
      - http://localhost:8080/push
  - group: group_2
    servers:
      - http://test:8082
      - http://test2:8181/test